export const AppConfig = {
  name: process.env.NEXT_PUBLIC_APP_NAME || "HR Portal",
  logo: process.env.NEXT_PUBLIC_APP_LOGO || "/logo.png",
  smLogo: process.env.NEXT_PUBLIC_APP_SM_LOGO || "https://perpetuitycapital.in/admin/pdf/logo.png",
  address: process.env.NEXT_PUBLIC_APP_ADDRESS || "Your Company Address",
  logoBgColor: process.env.LOGO_BG_COLOUR || '#121833',
  companyName: process.env.NEXT_PUBLIC_APP_COMPANY_NAME || "Perpetuity Capital",
  themePrimaryColor: process.env.NEXT_PUBLIC_THEME_COLOR || "#1e40af",
  companyLogo: process.env.NEXT_PUBLIC_COMPANY_LOGO || "/logo.png",  
  themeColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || "#00ab75",
  themeBackground: process.env.NEXT_PUBLIC_THEME_BG || "#131836",
  fontFamily: process.env.NEXT_PUBLIC_FONT || "Montserrat, sans-serif",
  textColor: process.env.NEXT_PUBLIC_TEXT_COLOR || "#ffffff",
  fontWeight: process.env.NEXT_PUBLIC_FONT_WEIGHT || "500",
};
